(* helper-v2v-input
 * Copyright (C) 2009-2025 Red Hat Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *)

open Printf
open Unix

open Std_utils
open Tools_utils
open Common_gettext.Gettext

open Types
open Utils

open Input

module OVA = struct
  let to_string options args = String.concat " " ("-i ova" :: args)

  let query_input_options () =
    printf (f_"No input options can be used in this mode.\n")

  (* RHBZ#1570407: VMware-generated OVA files found in the wild can
   * contain hrefs referencing snapshots.  The href will be something
   * like: <File href="disk1.vmdk"/> but the actual disk will be a
   * snapshot called something like "disk1.vmdk.000000000".
   *)
  let re_snapshot = PCRE.compile "\\.(\\d+)$"

  (* What a disk href resolved to: a file in the OVA, or a ready-made
   * qemu URI (used for chunked disks that we can present without
   * copying them).
   *)
  type resolved = File of OVA.file_ref | Uri of string

  let rec setup dir options args =
    if options.input_options <> [] then
      error (f_"no -io (input options) are allowed here");

    let ova =
      match args with
      | [ova] -> ova
      | _ ->
         error (f_"-i ova: expecting an OVA file name on the command line") in

    (* Check the OVA file is readable. *)
    access ova [R_OK];

    (* Extract ova file. *)
    let ova_t = OVA.parse_ova ova in

    (* Extract ovf file from ova. *)
    let ovf = OVA.get_ovf_file ova_t in

    (* Extract the manifest from *.mf files in the ova. *)
    let manifest = OVA.get_manifest ova_t in

    (* Verify checksums of files listed in the manifest. *)
    List.iter (
      fun (file_ref, csum) ->
        let filename, r =
          match file_ref with
          | OVA.LocalFile filename ->
             filename, Checksums.verify_checksum csum filename
          | OVA.TarFile (tar, filename) ->
             filename, Checksums.verify_checksum csum ~tar filename in
        match r with
        | Checksums.Good_checksum -> ()
        | Checksums.Mismatched_checksum (_, actual) ->
           error (f_"-i ova: corrupt OVA: checksum of disk %s does not match \
                     manifest (actual = %s, expected = %s)")
             filename actual (Checksums.string_of_csum_t csum)
        | Checksums.Missing_file ->
           (* RHBZ#1570407: Some OVA files generated by VMware
            * reference non-existent components in the *.mf file.
            * Generate a warning and ignore it.
            *)
           warning (f_"manifest has a checksum for non-existent file %s \
                       (ignored)")
             filename
    ) manifest;

    (* Parse the ovf file. *)
    let name, memory, vcpu, cpu_topology, firmware, disks, removables, nics =
      OVF.parse_ovf_from_ova ovf in

    let name =
      match name with
      | None ->
         warning (f_"could not parse ovf:Name from OVF document");
         name_from_disk ova
      | Some name -> name in

    (* Convert the disk hrefs into qemu URIs. *)
    let qemu_uris =
      List.map (
        fun { OVF.href; compressed; chunked } ->
          match find_file_or_snapshot ova_t href manifest chunked
                  compressed with
          | Uri uri -> uri
          | File file_ref ->
             match compressed, file_ref with
             | false, OVA.LocalFile filename ->
                filename

             | true, OVA.LocalFile filename ->
                (* The spec allows the file to be gzip-compressed, in
                 * which case we must uncompress it into a temporary.
                 *)
                let new_filename =
                  Filename.temp_file ~temp_dir:Utils.large_tmpdir
                    "ova" ".vmdk" in
                On_exit.unlink new_filename;
                let cmd =
                  sprintf "zcat %s > %s"
                    (quote filename) (quote new_filename) in
                if shell_command cmd <> 0 then
                  error (f_"error uncompressing %s, see earlier error messages")
                    filename;
                new_filename

             | false, OVA.TarFile (tar, filename) ->
                (* This is the tar optimization. *)
                let offset, size =
                  try OVA.get_tar_offet_and_size tar filename
                  with
                  | Not_found ->
                     error (f_"file ‘%s’ not found in the ova") filename
                  | Failure msg -> error (f_"%s") msg in
                (* QEMU requires size aligned to 512 bytes. This is safe because
                 * tar also works with 512 byte blocks.
                 *)
                let size = roundup64 size 512L in

                (* Workaround for libvirt bug RHBZ#1431652. *)
                let tar_path = absolute_path tar in

                let doc = [
                    "file", JSON.Dict [
                                "driver", JSON.String "raw";
                                "offset", JSON.Int offset;
                                "size", JSON.Int size;
                                "file", JSON.Dict [
                                            "driver", JSON.String "file";
                                            "filename", JSON.String tar_path]
                              ]
                  ] in
                let uri =
                  sprintf "json:%s"
                    (JSON.string_of_doc ~fmt:JSON.Compact doc) in
                uri

             | true, OVA.TarFile _ ->
                (* This should not happen since {!OVA} knows that
                 * qemu cannot handle compressed files here.
                 *)
                assert false
      ) disks in

    (* Create the source metadata. *)
    let s_disks = List.map (fun { OVF.source_disk } -> source_disk) disks in

    let source = {
      s_hypervisor = VMware;
      s_name = name;
      s_genid = None; (* XXX *)
      s_memory = memory;
      s_vcpu = vcpu;
      s_cpu_vendor = None;
      s_cpu_model = None;
      s_cpu_topology = cpu_topology;
      s_features = []; (* XXX *)
      s_firmware = firmware;
      s_uefi_secureboot = false;
      s_display = None; (* XXX *)
      s_sound = None;
      s_disks = s_disks;
      s_removables = removables;
      s_nics = nics;
    } in

    (* Run qemu-nbd for each disk. *)
    let uris =
      List.mapi (
        fun i qemu_uri ->
          let socket = sprintf "%s/in%d" dir i in
          On_exit.unlink socket;

          let cmd = QemuNBD.create qemu_uri in
          QemuNBD.set_snapshot cmd options.read_only; (* protective overlay *)
          QemuNBD.set_format cmd None; (* auto-detect format *)
          let _, pid = QemuNBD.run_unix socket cmd in
          On_exit.kill pid;

          NBD_URI.Unix (socket, None)
      ) qemu_uris in

    source, uris

  and find_file_or_snapshot ova_t href manifest chunked compressed =
    match OVA.resolve_href ova_t href with
    | Some f -> File f
    | None ->
       (* Find all files in the OVA called [<href>.\d+] *)
       let files = OVA.get_file_list ova_t in
       let snapshots =
         List.filter_map (
             function
             | OVA.LocalFile filename ->
                get_snapshot_if_matches href filename
             | OVA.TarFile (_, filename) ->
                get_snapshot_if_matches href filename
         ) files in
       if chunked then (
         (* DSP0243 chunked disk (ovf:chunkSize was present): these
          * must all be concatenated, in ascending order, to
          * reconstruct the disk -- unlike a VMware snapshot chain
          * (below) where only the highest-numbered file is wanted.
          *
          * Sort numerically (not as strings, since the suffix is
          * only matched as \d+ and might not be zero-padded), and
          * check that the chunks are contiguous starting from 0, so
          * a missing chunk is an error rather than a silently
          * corrupt disk.
          *)
         let numbered =
           List.map (
             fun snapshot ->
               match int_of_string_opt snapshot with
               | Some n -> (n, snapshot)
               | None ->
                  error (f_"-i ova: chunk number ‘%s’ of disk ‘%s’ is \
                            too large") snapshot href
           ) snapshots in
         let numbered = List.sort compare numbered in
         match numbered with
         | [] -> error_missing_href href
         | _ ->
            List.iteri (
              fun i (n, snapshot) ->
                if n <> i then
                  error (f_"-i ova: chunked disk ‘%s’ is missing chunk \
                            %d (or has duplicate chunks, found ‘%s’)")
                    href i snapshot
            ) numbered;
            chunked_disk ova_t href compressed (List.map snd numbered)
       )
       else (
         (* RHBZ#1570407: VMware-generated OVA files can reference a
          * snapshot chain; the highest-numbered file is the current
          * differencing disk and is the only one we want.
          *)
         let snapshots = List.sort (fun a b -> compare b a) snapshots in
         match snapshots with
         | [] -> error_missing_href href
         | snapshot::_ ->
            let href = sprintf "%s.%s" href snapshot in
            match OVA.resolve_href ova_t href with
            | None -> error_missing_href href
            | Some f -> File f
       )

  (* Present the (already sorted, contiguous) chunks of [href] as a
   * single disk.  Wherever possible this is done without copying any
   * data (see [flat_chunks_uri]), otherwise the chunks are
   * concatenated into a temporary file.
   *)
  and chunked_disk ova_t href compressed snapshots =
    let chunk_files =
      List.map (
        fun snapshot ->
          let chunk_href = sprintf "%s.%s" href snapshot in
          match OVA.resolve_href ova_t chunk_href with
          | None -> error_missing_href chunk_href
          | Some f -> f
      ) snapshots in

    (* A compressed disk needs the whole stream, so it must be
     * concatenated and then uncompressed.
     *)
    let uri = if compressed then None else flat_chunks_uri chunk_files in
    match uri with
    | Some uri ->
       debug "-i ova: presenting chunked disk %s as %d extents \
              without copying" href (List.length chunk_files);
       Uri uri
    | None ->
       debug "-i ova: concatenating %d chunks of disk %s into a \
              temporary file" (List.length chunk_files) href;
       File (concat_chunks href chunk_files)

  (* Describe the chunks as one disk using a small VMDK descriptor
   * with one FLAT extent per chunk, pointing straight into the OVA
   * (or into the chunk files), so no disk data is copied.  The
   * descriptor exposes the chunks back to back as a raw block
   * device holding the disk image (usually a streamOptimized VMDK),
   * which is then opened on top of the descriptor as usual.
   *
   * Extents are counted in 512 byte sectors, so this only works if
   * every chunk except the last is a whole number of sectors.
   * DSP0243 does not require that, so return [None] when it is not
   * the case (or if anything looks unusual) and let the caller fall
   * back to copying.
   *)
  and flat_chunks_uri chunk_files =
    try
      let n = List.length chunk_files in
      let extents =
        List.mapi (
          fun i chunk ->
            let path, offset, size, in_tar =
              match chunk with
              | OVA.LocalFile filename ->
                 let size = (LargeFile.stat filename).LargeFile.st_size in
                 (absolute_path filename, 0L, size, false)
              | OVA.TarFile (tar, filename) ->
                 let offset, size = OVA.get_tar_offet_and_size tar filename in
                 (absolute_path tar, offset, size, true) in
            (* Tar pads the last member to a whole block, which is
             * what the tar optimization above relies on too.
             *)
            let size =
              if i = n-1 && in_tar then roundup64 size 512L else size in
            (path, offset, size)
        ) chunk_files in
      let usable (path, offset, size) =
        size > 0L &&
        Int64.rem size 512L = 0L &&
        Int64.rem offset 512L = 0L &&
        not (String.contains path '"' || String.contains path '\n') in
      if not (List.for_all usable extents) then None
      else (
        let descriptor = Buffer.create 1024 in
        bprintf descriptor "# Disk DescriptorFile\n\
                            version=1\n\
                            CID=fffffffe\n\
                            parentCID=ffffffff\n\
                            createType=\"monolithicFlat\"\n\
                            \n\
                            # Extent description\n";
        List.iter (
          fun (path, offset, size) ->
            bprintf descriptor "RW %Ld FLAT \"%s\" %Ld\n"
              (Int64.div size 512L) path (Int64.div offset 512L)
        ) extents;

        let tmpfile =
          Filename.temp_file ~temp_dir:Utils.large_tmpdir
            "ova-chunks" ".vmdk" in
        On_exit.unlink tmpfile;
        let chan = open_out tmpfile in
        output_string chan (Buffer.contents descriptor);
        close_out chan;

        (* No outer "driver": the payload format is probed as for any
         * other disk.
         *)
        let doc = [
            "file", JSON.Dict [
                        "driver", JSON.String "vmdk";
                        "file", JSON.Dict [
                                    "driver", JSON.String "file";
                                    "filename", JSON.String tmpfile]
                      ]
          ] in
        Some (sprintf "json:%s" (JSON.string_of_doc ~fmt:JSON.Compact doc))
      )
    with Not_found | Failure _ | Unix_error _ -> None

  (* Fallback: concatenate the chunk files for [href] into a single
   * temporary file and return it as a LocalFile.  This needs
   * roughly the size of the disk in temporary space and gives up the
   * tar zero-copy optimization, the same tradeoff already made for
   * compressed disks below.
   *)
  and concat_chunks href chunk_files =
    let tmpfile =
      Filename.temp_file ~temp_dir:Utils.large_tmpdir "ova-chunks" ".vmdk" in
    On_exit.unlink tmpfile;

    List.iter (
      fun chunk ->
        let cmd =
          match chunk with
          | OVA.LocalFile filename ->
             sprintf "cat %s >> %s" (quote filename) (quote tmpfile)
          | OVA.TarFile (tar, filename) ->
             sprintf "tar -xf %s -O %s >> %s"
               (quote tar) (quote filename) (quote tmpfile) in
        if shell_command cmd <> 0 then
          error (f_"-i ova: error reconstructing chunked disk ‘%s’, see \
                    earlier error messages") href
    ) chunk_files;

    OVA.LocalFile tmpfile

  (* If [filename] matches [<href>.\d+] then return [Some snapshot]. *)
  and get_snapshot_if_matches href filename =
    if PCRE.matches re_snapshot filename then (
      let snapshot = PCRE.sub 1 in
      let suffix = sprintf "%s.%s" href snapshot in
      if String.ends_with ~suffix filename then
        Some snapshot
      else
        None
    )
    else None

  and error_missing_href : 'a. string -> 'a = fun href ->
    error (f_"-i ova: OVF references file ‘%s’ which was not found \
              in the OVA archive") href
end
